export const artists = [
    {
        paramsName: "animakid",
        artistNameEn: "Animakid",
        artistNameFa: "بچه انیما",
        bioEn: "The Internet's Friendliest Designer Kid.",
        bioFa: ".دوستانه ترین بچه طراح اینترنت",
        topImage: "artist-page.jpg",
        avatar: "animakid-avatar.png",
        achievements: {
            volume: 250,
            soldNFTs: 50,
            followers: 3000
        },
        createdCount: 9,
        ownedCount: 4,
        collectionCount: 2,
        createdTabInfo: [
            {
              id: 1,
              href: "/",
              image: "distant-galaxy.jpg",
              titleEn: "Distant Galaxy",
              titleFa: "کهکشان دوردست",
              price: "1.63",
              highestBid: "0.33",
            },
            {
              id: 2,
              href: "/",
              image: "life-on-edena.jpg",
              titleEn: "Life On Edena",
              titleFa: "زندگی در ادن",
              price: "2.01",
              highestBid: "0.58",
            },
            {
              id: 3,
              href: "/",
              image: "astro-fiction.jpg",
              titleEn: "AstroFiction",
              titleFa: "داستان نجومی",
              price: "1.52",
              highestBid: "0.26",
            },
            {
              id: 4,
              href: "/",
              image: "crypto-city.jpg",
              titleEn: "CryptoCity",
              titleFa: "شهر کریپتو",
              price: "1.81",
              highestBid: "0.43",
            },
            {
              id: 5,
              href: "/",
              image: "colorful-dog.jpg",
              titleEn: "ColorfulDog 0524",
              titleFa: "سگ رنگارنگ 0524",
              price: "1.31",
              highestBid: "0.19",
            },
            {
              id: 6,
              href: "/",
              image: "space-tales.jpg",
              titleEn: "Space Tales",
              titleFa: "داستان های فضایی",
              price: "1.82",
              highestBid: "0.56",
            },
            {
              id: 7,
              href: "/",
              image: "cherry-blossom-girl.jpg",
              titleEn: "Cherry Blossom Girl 037",
              titleFa: "دختر شکوفه گیلاس 037",
              price: "1.79",
              highestBid: "0.48",
            },
            {
              id: 8,
              href: "/",
              image: "dancing-robots.jpg",
              titleEn: "Dancing Robots 0987",
              titleFa: "ربات های رقصنده 0987",
              price: "1.61",
              highestBid: "0.35",
            },
            {
              id: 9,
              href: "/",
              image: "collectibles-category.jpg",
              titleEn: "IceCream Ape ",
              titleFa: "میمون بستنی",
              price: "1.46",
              highestBid: "0.29",
            },
        ],
        ownedTabInfo: [
            {
              id: 1,
              href: "/",
              image: "nft-2.jpeg",
              titleEn: "Delicious Pie 61",
              titleFa: "پای خوشمزه 61",
              price: "1.55",
              highestBid: "0.39",
            },
            {
              id: 2,
              href: "/",
              image: "nft-18.jpeg",
              titleEn: "Damavand 13",
              titleFa: "دماوند 13",
              price: "1.78",
              highestBid: "0.61",
            },
            {
              id: 3,
              href: "/",
              image: "nft-24.jpeg",
              titleEn: "peace of mind",
              titleFa: "آرامش خاطر",
              price: "1.29",
              highestBid: "0.18",
            },
            {
              id: 4,
              href: "/",
              image: "nft-40.jpeg",
              titleEn: "Childhood",
              titleFa: "دوران کودکی",
              price: "1.55",
              highestBid: "0.39",
            },
        ],
        collectionTabInfo: [
            {
              id: 1,
              href: "/",
              imageMain: "photography-category.jpg",
              topLayerImage: "camera.png",
              titleEn: "Photography",
              titleFa: "عکاسی",
            },
            {
              id: 2,
              href: "/",
              imageMain: "music-category.jpg",
              topLayerImage: "music-notes.png",
              titleEn: "Music",
              titleFa: "موسیقی",
            },
        ],
    },
    {
      paramsName: "mrfox",
      artistNameEn: "MrFox",
      artistNameFa: "آقای فاکس",
      bioEn: "A digital artist known for merging nature with technology.",
      bioFa: ".یک هنرمند دیجیتال که طبیعت را با فناوری ادغام می‌کند",
      topImage: "CHANGE-IMAGE",
      avatar: "CHANGE-IMAGE",
      achievements: {
          volume: 523,
          soldNFTs: 45,
          followers: 6882
      },
      createdCount: 8,
      ownedCount: 3,
      collectionCount: 5,
      createdTabInfo: [
          {
              id: 1,
              href: "/",
              image: "CHANGE-IMAGE",
              titleEn: "Eternal Vision",
              titleFa: "چشم انداز ابدی",
              price: "3.45",
              highestBid: "0.88",
          },
          {
              id: 2,
              href: "/",
              image: "CHANGE-IMAGE",
              titleEn: "Digital Symphony",
              titleFa: "سمفونی دیجیتال",
              price: "2.98",
              highestBid: "0.56",
          },
          {
              id: 3,
              href: "/",
              image: "CHANGE-IMAGE",
              titleEn: "Green Horizon",
              titleFa: "افق سبز",
              price: "4.12",
              highestBid: "0.72",
          },
          {
              id: 4,
              href: "/",
              image: "CHANGE-IMAGE",
              titleEn: "Techno Dreams",
              titleFa: "رویاهای تکنولوژیکی",
              price: "3.33",
              highestBid: "0.61",
          },
          {
              id: 5,
              href: "/",
              image: "CHANGE-IMAGE",
              titleEn: "Whispering Woods",
              titleFa: "زمزمه‌های جنگل",
              price: "2.74",
              highestBid: "0.45",
          },
          {
              id: 6,
              href: "/",
              image: "CHANGE-IMAGE",
              titleEn: "Future Roots",
              titleFa: "ریشه‌های آینده",
              price: "3.86",
              highestBid: "0.77",
          },
          {
              id: 7,
              href: "/",
              image: "CHANGE-IMAGE",
              titleEn: "Cyber Forest",
              titleFa: "جنگل سایبری",
              price: "2.95",
              highestBid: "0.63",
          },
          {
              id: 8,
              href: "/",
              image: "CHANGE-IMAGE",
              titleEn: "Fox In The City",
              titleFa: "روباه در شهر",
              price: "3.29",
              highestBid: "0.82",
          },
          {
              id: 9,
              href: "/",
              image: "CHANGE-IMAGE",
              titleEn: "Virtual Wilderness",
              titleFa: "بیابان مجازی",
              price: "2.47",
              highestBid: "0.50",
          },
      ],
      ownedTabInfo: [
          {
              id: 1,
              href: "/",
              image: "CHANGE-IMAGE",
              titleEn: "Winter Light",
              titleFa: "نور زمستان",
              price: "2.33",
              highestBid: "0.77",
          },
          {
              id: 2,
              href: "/",
              image: "CHANGE-IMAGE",
              titleEn: "Mechanical River",
              titleFa: "رودخانه مکانیکی",
              price: "1.98",
              highestBid: "0.55",
          },
          {
              id: 3,
              href: "/",
              image: "CHANGE-IMAGE",
              titleEn: "Fox Tale",
              titleFa: "داستان روباه",
              price: "1.65",
              highestBid: "0.40",
          },
          {
              id: 4,
              href: "/",
              image: "CHANGE-IMAGE",
              titleEn: "Echoes of Nature",
              titleFa: "طنین طبیعت",
              price: "2.12",
              highestBid: "0.61",
          },
      ],
      collectionTabInfo: [
          {
              id: 1,
              href: "/",
              imageMain: "CHANGE-IMAGE",
              topLayerImage: "CHANGE-IMAGE",
              titleEn: "Art",
              titleFa: "هنر",
          },
          {
              id: 2,
              href: "/",
              imageMain: "CHANGE-IMAGE",
              topLayerImage: "CHANGE-IMAGE",
              titleEn: "Nature",
              titleFa: "طبیعت",
          },
          {
              id: 3,
              href: "/",
              imageMain: "CHANGE-IMAGE",
              topLayerImage: "CHANGE-IMAGE",
              titleEn: "Photography",
              titleFa: "عکاسی",
          },
          {
              id: 4,
              href: "/",
              imageMain: "CHANGE-IMAGE",
              topLayerImage: "CHANGE-IMAGE",
              titleEn: "Collectibles",
              titleFa: "کلکسیون‌ها",
          },
          {
              id: 5,
              href: "/",
              imageMain: "CHANGE-IMAGE",
              topLayerImage: "CHANGE-IMAGE",
              titleEn: "Virtual Worlds",
              titleFa: "دنیاهای مجازی",
          },
      ],
  },
  {
      paramsName: "shroomie",
      artistNameEn: "Shroomie",
      artistNameFa: "شروومی",
      bioEn: "An artist inspired by the mysticism of fungi.",
      bioFa: ".هنرمندی الهام گرفته از رمز و راز قارچ‌ها",
      topImage: "CHANGE-IMAGE",
      avatar: "CHANGE-IMAGE",
      achievements: {
          volume: 765,
          soldNFTs: 89,
          followers: 4212
      },
      createdCount: 10,
      ownedCount: 4,
      collectionCount: 6,
      createdTabInfo: [
          {
              id: 1,
              href: "/",
              image: "CHANGE-IMAGE",
              titleEn: "Mushroom Kingdom",
              titleFa: "قلمرو قارچ‌ها",
              price: "4.12",
              highestBid: "0.91",
          },
          {
              id: 2,
              href: "/",
              image: "CHANGE-IMAGE",
              titleEn: "Mystic Growth",
              titleFa: "رشد اسرارآمیز",
              price: "3.98",
              highestBid: "0.78",
          },
          {
              id: 3,
              href: "/",
              image: "CHANGE-IMAGE",
              titleEn: "Fungi Dreams",
              titleFa: "رویاهای قارچی",
              price: "4.55",
              highestBid: "0.99",
          },
          {
              id: 4,
              href: "/",
              image: "CHANGE-IMAGE",
              titleEn: "Shroom Symphony",
              titleFa: "سمفونی شرووم",
              price: "2.89",
              highestBid: "0.66",
          },
          {
              id: 5,
              href: "/",
              image: "CHANGE-IMAGE",
              titleEn: "Enchanted Grove",
              titleFa: "درختزار مسحور",
              price: "3.49",
              highestBid: "0.72",
          },
          {
              id: 6,
              href: "/",
              image: "CHANGE-IMAGE",
              titleEn: "Secret Forest",
              titleFa: "جنگل مخفی",
              price: "2.67",
              highestBid: "0.52",
          },
          {
              id: 7,
              href: "/",
              image: "CHANGE-IMAGE",
              titleEn: "Golden Cap",
              titleFa: "کلاه طلایی",
              price: "4.01",
              highestBid: "0.84",
          },
          {
              id: 8,
              href: "/",
              image: "CHANGE-IMAGE",
              titleEn: "Magical Spores",
              titleFa: "اسپورهای جادویی",
              price: "3.75",
              highestBid: "0.67",
          },
          {
              id: 9,
              href: "/",
              image: "CHANGE-IMAGE",
              titleEn: "Hidden Realms",
              titleFa: "قلمروهای مخفی",
              price: "2.85",
              highestBid: "0.60",
          },
      ],
      ownedTabInfo: [
          {
              id: 1,
              href: "/",
              image: "CHANGE-IMAGE",
              titleEn: "Forest Whisper",
              titleFa: "زمزمه جنگل",
              price: "1.79",
              highestBid: "0.41",
          },
          {
              id: 2,
              href: "/",
              image: "CHANGE-IMAGE",
              titleEn: "Mossy Stones",
              titleFa: "سنگ‌های خزه‌ای",
              price: "1.95",
              highestBid: "0.45",
          },
          {
              id: 3,
              href: "/",
              image: "CHANGE-IMAGE",
              titleEn: "Glowing Shrooms",
              titleFa: "شرووم‌های درخشان",
              price: "2.56",
              highestBid: "0.58",
          },
          {
              id: 4,
              href: "/",
              image: "CHANGE-IMAGE",
              titleEn: "Deep Forest",
              titleFa: "جنگل عمیق",
              price: "1.88",
              highestBid: "0.36",
          },
      ],
      collectionTabInfo: [
          {
              id: 1,
              href: "/",
              imageMain: "CHANGE-IMAGE",
              topLayerImage: "CHANGE-IMAGE",
              titleEn: "Nature",
              titleFa: "طبیعت",
          },
          {
              id: 2,
              href: "/",
              imageMain: "CHANGE-IMAGE",
              topLayerImage: "CHANGE-IMAGE",
              titleEn: "Magic",
              titleFa: "جادو",
          },
          {
              id: 3,
              href: "/",
              imageMain: "CHANGE-IMAGE",
              topLayerImage: "CHANGE-IMAGE",
              titleEn: "Fungi",
              titleFa: "قارچ",
          },
          {
              id: 4,
              href: "/",
              imageMain: "CHANGE-IMAGE",
              topLayerImage: "CHANGE-IMAGE",
              titleEn: "Mystery",
              titleFa: "راز",
          },
          {
              id: 5,
              href: "/",
              imageMain: "CHANGE-IMAGE",
              topLayerImage: "CHANGE-IMAGE",
              titleEn: "Enchantments",
              titleFa: "افسون‌ها",
          },
      ],
  },
  {
      paramsName: "bekind2robots",
      artistNameEn: "BeKind2Robots",
      artistNameFa: "مهربان با ربات‌ها",
      bioEn: "An artist advocating for empathy towards machines.",
      bioFa: ".هنرمندی که از همدلی با ماشین‌ها دفاع می‌کند",
      topImage: "CHANGE-IMAGE",
      avatar: "CHANGE-IMAGE",
      achievements: {
          volume: 411,
          soldNFTs: 35,
          followers: 3020
      },
      createdCount: 7,
      ownedCount: 2,
      collectionCount: 4,
      createdTabInfo: [
          {
              id: 1,
              href: "/",
              image: "CHANGE-IMAGE",
              titleEn: "Robot Dreams",
              titleFa: "رویاهای ربات",
              price: "2.19",
              highestBid: "0.77",
          },
          {
              id: 2,
              href: "/",
              image: "CHANGE-IMAGE",
              titleEn: "Mechanical Heart",
              titleFa: "قلب مکانیکی",
              price: "3.42",
              highestBid: "0.99",
          },
          {
              id: 3,
              href: "/",
              image: "CHANGE-IMAGE",
              titleEn: "Digital Humanity",
              titleFa: "انسانیت دیجیتال",
              price: "4.21",
              highestBid: "1.23",
          },
          {
              id: 4,
              href: "/",
              image: "CHANGE-IMAGE",
              titleEn: "Circuit Soul",
              titleFa: "روح مدار",
              price: "2.78",
              highestBid: "0.65",
          },
          {
              id: 5,
              href: "/",
              image: "CHANGE-IMAGE",
              titleEn: "Code and Compassion",
              titleFa: "کد و دلسوزی",
              price: "3.39",
              highestBid: "0.88",
          },
          {
              id: 6,
              href: "/",
              image: "CHANGE-IMAGE",
              titleEn: "Binary Love",
              titleFa: "عشق دودویی",
              price: "2.54",
              highestBid: "0.58",
          },
          {
              id: 7,
              href: "/",
              image: "CHANGE-IMAGE",
              titleEn: "Steel Emotions",
              titleFa: "احساسات فولادی",
              price: "3.21",
              highestBid: "0.91",
          },
      ],
      ownedTabInfo: [
          {
              id: 1,
              href: "/",
              image: "CHANGE-IMAGE",
              titleEn: "Robotica",
              titleFa: "روباتیکا",
              price: "1.65",
              highestBid: "0.40",
          },
          {
              id: 2,
              href: "/",
              image: "CHANGE-IMAGE",
              titleEn: "Artificial Sentiment",
              titleFa: "احساسات مصنوعی",
              price: "1.85",
              highestBid: "0.50",
          },
      ],
      collectionTabInfo: [
          {
              id: 1,
              href: "/",
              imageMain: "CHANGE-IMAGE",
              topLayerImage: "CHANGE-IMAGE",
              titleEn: "Robots",
              titleFa: "ربات‌ها",
          },
          {
              id: 2,
              href: "/",
              imageMain: "CHANGE-IMAGE",
              topLayerImage: "CHANGE-IMAGE",
              titleEn: "Technology",
              titleFa: "فناوری",
          },
          {
              id: 3,
              href: "/",
              imageMain: "CHANGE-IMAGE",
              topLayerImage: "CHANGE-IMAGE",
              titleEn: "AI",
              titleFa: "هوش مصنوعی",
          },
          {
              id: 4,
              href: "/",
              imageMain: "CHANGE-IMAGE",
              topLayerImage: "CHANGE-IMAGE",
              titleEn: "Futurism",
              titleFa: "آینده‌گرایی",
          },
      ],
  },
  {
    paramsName: "keepitreal",
    artistNameEn: "Keepitreal",
    artistNameFa: "حقیقت را بگو",
    bioEn: "A visual storyteller who captures the essence of authenticity.",
    bioFa: ".یک داستان‌سرای بصری که جوهره اصالت را به تصویر می‌کشد",
    topImage: "CHANGE-IMAGE",
    avatar: "CHANGE-IMAGE",
    achievements: {
        volume: 632,
        soldNFTs: 55,
        followers: 9123
    },
    createdCount: 9,
    ownedCount: 4,
    collectionCount: 5,
    createdTabInfo: [
        {
            id: 1,
            href: "/",
            image: "CHANGE-IMAGE",
            titleEn: "Raw Reality",
            titleFa: "واقعیت خالص",
            price: "3.87",
            highestBid: "0.85",
        },
        {
            id: 2,
            href: "/",
            image: "CHANGE-IMAGE",
            titleEn: "True Vision",
            titleFa: "چشم‌انداز واقعی",
            price: "4.12",
            highestBid: "0.93",
        },
        {
            id: 3,
            href: "/",
            image: "CHANGE-IMAGE",
            titleEn: "Honest Moments",
            titleFa: "لحظات صادقانه",
            price: "2.65",
            highestBid: "0.61",
        },
        {
            id: 4,
            href: "/",
            image: "CHANGE-IMAGE",
            titleEn: "Unfiltered Soul",
            titleFa: "روح بدون فیلتر",
            price: "3.49",
            highestBid: "0.77",
        },
        {
            id: 5,
            href: "/",
            image: "CHANGE-IMAGE",
            titleEn: "Behind The Mask",
            titleFa: "پشت نقاب",
            price: "4.27",
            highestBid: "1.05",
        },
        {
            id: 6,
            href: "/",
            image: "CHANGE-IMAGE",
            titleEn: "Pure Expression",
            titleFa: "بیان خالص",
            price: "3.19",
            highestBid: "0.70",
        },
        {
            id: 7,
            href: "/",
            image: "CHANGE-IMAGE",
            titleEn: "Authentic Vibes",
            titleFa: "ارتعاشات اصیل",
            price: "3.89",
            highestBid: "0.92",
        },
        {
            id: 8,
            href: "/",
            image: "CHANGE-IMAGE",
            titleEn: "The Real Deal",
            titleFa: "معامله واقعی",
            price: "4.11",
            highestBid: "0.99",
        },
        {
            id: 9,
            href: "/",
            image: "CHANGE-IMAGE",
            titleEn: "Sincere Light",
            titleFa: "نور صادقانه",
            price: "2.93",
            highestBid: "0.69",
        },
    ],
    ownedTabInfo: [
        {
            id: 1,
            href: "/",
            image: "CHANGE-IMAGE",
            titleEn: "True Colors",
            titleFa: "رنگ‌های واقعی",
            price: "2.74",
            highestBid: "0.66",
        },
        {
            id: 2,
            href: "/",
            image: "CHANGE-IMAGE",
            titleEn: "Genuine Glow",
            titleFa: "درخشش اصیل",
            price: "3.01",
            highestBid: "0.81",
        },
        {
            id: 3,
            href: "/",
            image: "CHANGE-IMAGE",
            titleEn: "Naked Truth",
            titleFa: "حقیقت برهنه",
            price: "2.56",
            highestBid: "0.63",
        },
        {
            id: 4,
            href: "/",
            image: "CHANGE-IMAGE",
            titleEn: "Honest Path",
            titleFa: "مسیر صادقانه",
            price: "2.81",
            highestBid: "0.71",
        },
    ],
    collectionTabInfo: [
        {
            id: 1,
            href: "/",
            imageMain: "CHANGE-IMAGE",
            topLayerImage: "CHANGE-IMAGE",
            titleEn: "Truth",
            titleFa: "حقیقت",
        },
        {
            id: 2,
            href: "/",
            imageMain: "CHANGE-IMAGE",
            topLayerImage: "CHANGE-IMAGE",
            titleEn: "Reality",
            titleFa: "واقعیت",
        },
        {
            id: 3,
            href: "/",
            imageMain: "CHANGE-IMAGE",
            topLayerImage: "CHANGE-IMAGE",
            titleEn: "Moments",
            titleFa: "لحظات",
        },
        {
            id: 4,
            href: "/",
            imageMain: "CHANGE-IMAGE",
            topLayerImage: "CHANGE-IMAGE",
            titleEn: "Expression",
            titleFa: "بیان",
        },
        {
            id: 5,
            href: "/",
            imageMain: "CHANGE-IMAGE",
            topLayerImage: "CHANGE-IMAGE",
            titleEn: "Authenticity",
            titleFa: "اصالت",
        },
    ],
  },
  {
    paramsName: "digilab",
    artistNameEn: "DigiLab",
    artistNameFa: "دیجی لب",
    bioEn: "A visionary creator blending digital art with futuristic design.",
    bioFa: ".خالق بصیر که هنر دیجیتال را با طراحی آینده‌گرا ترکیب می‌کند",
    topImage: "CHANGE-IMAGE",
    avatar: "CHANGE-IMAGE",
    achievements: {
        volume: 712,
        soldNFTs: 69,
        followers: 8420
    },
    createdCount: 10,
    ownedCount: 2,
    collectionCount: 4,
    createdTabInfo: [
        {
            id: 1,
            href: "/",
            image: "CHANGE-IMAGE",
            titleEn: "Digital Dreams",
            titleFa: "رویاهای دیجیتال",
            price: "5.46",
            highestBid: "0.89",
        },
        {
            id: 2,
            href: "/",
            image: "CHANGE-IMAGE",
            titleEn: "Future Horizon",
            titleFa: "افق آینده",
            price: "6.78",
            highestBid: "0.95",
        },
        {
            id: 3,
            href: "/",
            image: "CHANGE-IMAGE",
            titleEn: "Cyber Essence",
            titleFa: "جوهر سایبری",
            price: "4.12",
            highestBid: "0.67",
        },
        {
            id: 4,
            href: "/",
            image: "CHANGE-IMAGE",
            titleEn: "Virtual Universe",
            titleFa: "جهان مجازی",
            price: "5.89",
            highestBid: "0.77",
        },
        {
            id: 5,
            href: "/",
            image: "CHANGE-IMAGE",
            titleEn: "Holographic Vision",
            titleFa: "دید هولوگرافیک",
            price: "6.54",
            highestBid: "0.92",
        },
        {
            id: 6,
            href: "/",
            image: "CHANGE-IMAGE",
            titleEn: "Synthetic Realm",
            titleFa: "قلمرو مصنوعی",
            price: "4.98",
            highestBid: "0.81",
        },
        {
            id: 7,
            href: "/",
            image: "CHANGE-IMAGE",
            titleEn: "Digital Symphony",
            titleFa: "سمفونی دیجیتال",
            price: "5.21",
            highestBid: "0.74",
        },
        {
            id: 8,
            href: "/",
            image: "CHANGE-IMAGE",
            titleEn: "Techno Reality",
            titleFa: "واقعیت تکنولوژیک",
            price: "4.39",
            highestBid: "0.68",
        },
        {
            id: 9,
            href: "/",
            image: "CHANGE-IMAGE",
            titleEn: "Quantum Future",
            titleFa: "آینده کوانتومی",
            price: "5.96",
            highestBid: "0.83",
        },
    ],
    ownedTabInfo: [
        {
            id: 1,
            href: "/",
            image: "CHANGE-IMAGE",
            titleEn: "Code Matrix",
            titleFa: "ماتریس کد",
            price: "3.45",
            highestBid: "0.56",
        },
        {
            id: 2,
            href: "/",
            image: "CHANGE-IMAGE",
            titleEn: "Digital Core",
            titleFa: "هسته دیجیتال",
            price: "4.67",
            highestBid: "0.73",
        },
        {
            id: 3,
            href: "/",
            image: "CHANGE-IMAGE",
            titleEn: "Virtual Loop",
            titleFa: "حلقه مجازی",
            price: "3.12",
            highestBid: "0.49",
        },
        {
            id: 4,
            href: "/",
            image: "CHANGE-IMAGE",
            titleEn: "Neon Network",
            titleFa: "شبکه نئونی",
            price: "3.89",
            highestBid: "0.65",
        },
    ],
    collectionTabInfo: [
        {
            id: 1,
            href: "/",
            imageMain: "CHANGE-IMAGE",
            topLayerImage: "CHANGE-IMAGE",
            titleEn: "Collectibles",
            titleFa: "کلکسیونی‌ها",
        },
        {
            id: 2,
            href: "/",
            imageMain: "CHANGE-IMAGE",
            topLayerImage: "CHANGE-IMAGE",
            titleEn: "Art",
            titleFa: "هنر",
        },
        {
            id: 3,
            href: "/",
            imageMain: "CHANGE-IMAGE",
            topLayerImage: "CHANGE-IMAGE",
            titleEn: "Virtual Worlds",
            titleFa: "جهان‌های مجازی",
        },
        {
            id: 4,
            href: "/",
            imageMain: "CHANGE-IMAGE",
            topLayerImage: "CHANGE-IMAGE",
            titleEn: "Technology",
            titleFa: "تکنولوژی",
        },
    ],
},
{
  paramsName: "gravityone",
  artistNameEn: "GravityOne",
  artistNameFa: "گراویتی وان",
  bioEn: "An explorer of space and gravity through digital artistry.",
  bioFa: ".یک کاوشگر فضا و جاذبه از طریق هنر دیجیتال",
  topImage: "CHANGE-IMAGE",
  avatar: "CHANGE-IMAGE",
  achievements: {
      volume: 615,
      soldNFTs: 76,
      followers: 7302
  },
  createdCount: 11,
  ownedCount: 3,
  collectionCount: 5,
  createdTabInfo: [
      {
          id: 1,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Galactic Voyage",
          titleFa: "سفر کهکشانی",
          price: "6.89",
          highestBid: "0.94",
      },
      {
          id: 2,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Orbital Harmony",
          titleFa: "هارمونی مداری",
          price: "5.34",
          highestBid: "0.67",
      },
      {
          id: 3,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Gravity's Touch",
          titleFa: "لمس جاذبه",
          price: "7.56",
          highestBid: "0.99",
      },
      {
          id: 4,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Cosmic Pulse",
          titleFa: "ضربان کیهانی",
          price: "4.72",
          highestBid: "0.51",
      },
      {
          id: 5,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Infinite Space",
          titleFa: "فضای بی‌نهایت",
          price: "6.12",
          highestBid: "0.88",
      },
      {
          id: 6,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Stellar Drift",
          titleFa: "رانش ستاره‌ای",
          price: "5.79",
          highestBid: "0.72",
      },
      {
          id: 7,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Nebula Dance",
          titleFa: "رقص سحابی",
          price: "4.23",
          highestBid: "0.45",
      },
      {
          id: 8,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Planetary Rhythm",
          titleFa: "ریتم سیاره‌ای",
          price: "6.54",
          highestBid: "0.81",
      },
      {
          id: 9,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Astral Glow",
          titleFa: "درخشش نجومی",
          price: "5.38",
          highestBid: "0.69",
      },
  ],
  ownedTabInfo: [
      {
          id: 1,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Celestial Orbit",
          titleFa: "مدار آسمانی",
          price: "3.67",
          highestBid: "0.56",
      },
      {
          id: 2,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Eternal Sky",
          titleFa: "آسمان جاویدان",
          price: "4.12",
          highestBid: "0.64",
      },
      {
          id: 3,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Gravitational Pull",
          titleFa: "کشیدن جاذبه",
          price: "3.89",
          highestBid: "0.53",
      },
      {
          id: 4,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Space Continuum",
          titleFa: "پیوستار فضا",
          price: "4.78",
          highestBid: "0.72",
      },
  ],
  collectionTabInfo: [
      {
          id: 1,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Art",
          titleFa: "هنر",
      },
      {
          id: 2,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Virtual Worlds",
          titleFa: "جهان‌های مجازی",
      },
      {
          id: 3,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Music",
          titleFa: "موسیقی",
      },
      {
          id: 4,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Collectibles",
          titleFa: "کلکسیونی‌ها",
      },
      {
          id: 5,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Photography",
          titleFa: "عکاسی",
      },
  ],
},
{
  paramsName: "juanie",
  artistNameEn: "Juanie",
  artistNameFa: "خوانی",
  bioEn: "A visionary artist exploring identity through vibrant visual narratives.",
  bioFa: ".یک هنرمند خلاق که هویت را از طریق روایت‌های بصری پر جنب و جوش کاوش می‌کند",
  topImage: "CHANGE-IMAGE",
  avatar: "CHANGE-IMAGE",
  achievements: {
      volume: 493,
      soldNFTs: 43,
      followers: 4671
  },
  createdCount: 8,
  ownedCount: 2,
  collectionCount: 4,
  createdTabInfo: [
      {
          id: 1,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Vivid Reflections",
          titleFa: "بازتاب‌های زنده",
          price: "7.21",
          highestBid: "0.83",
      },
      {
          id: 2,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Eternal Moment",
          titleFa: "لحظه ابدی",
          price: "6.45",
          highestBid: "0.74",
      },
      {
          id: 3,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "City of Dreams",
          titleFa: "شهر رویاها",
          price: "5.32",
          highestBid: "0.65",
      },
      {
          id: 4,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Unseen Horizons",
          titleFa: "افق‌های ناپیدا",
          price: "6.72",
          highestBid: "0.78",
      },
      {
          id: 5,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Lost in Colors",
          titleFa: "گم شده در رنگ‌ها",
          price: "4.89",
          highestBid: "0.55",
      },
      {
          id: 6,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Silent Symphony",
          titleFa: "سمفونی خاموش",
          price: "5.96",
          highestBid: "0.71",
      },
      {
          id: 7,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Echoes of Life",
          titleFa: "طنین زندگی",
          price: "6.83",
          highestBid: "0.77",
      },
      {
          id: 8,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Fragmented Soul",
          titleFa: "روح متلاشی",
          price: "5.64",
          highestBid: "0.68",
      },
      {
          id: 9,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Winds of Change",
          titleFa: "بادهای تغییر",
          price: "4.92",
          highestBid: "0.53",
      },
  ],
  ownedTabInfo: [
      {
          id: 1,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Distant Whispers",
          titleFa: "زمزمه‌های دور",
          price: "3.67",
          highestBid: "0.42",
      },
      {
          id: 2,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Hidden Gems",
          titleFa: "جواهرات پنهان",
          price: "4.21",
          highestBid: "0.56",
      },
      {
          id: 3,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Faded Memories",
          titleFa: "خاطرات محو",
          price: "3.89",
          highestBid: "0.49",
      },
      {
          id: 4,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Journey Home",
          titleFa: "سفر به خانه",
          price: "4.58",
          highestBid: "0.61",
      },
  ],
  collectionTabInfo: [
      {
          id: 1,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Art",
          titleFa: "هنر",
      },
      {
          id: 2,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Collectibles",
          titleFa: "کلکسیونی‌ها",
      },
      {
          id: 3,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Music",
          titleFa: "موسیقی",
      },
      {
          id: 4,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Photography",
          titleFa: "عکاسی",
      },
  ],
},
{
  paramsName: "bluewhale",
  artistNameEn: "BlueWhale",
  artistNameFa: "نهنگ آبی",
  bioEn: "An artist diving into the depths of imagination to create powerful visual experiences.",
  bioFa: ".هنرمندی که در عمق تخیل غواصی می‌کند تا تجربیات بصری قدرتمندی خلق کند",
  topImage: "CHANGE-IMAGE",
  avatar: "CHANGE-IMAGE",
  achievements: {
      volume: 684,
      soldNFTs: 76,
      followers: 7482
  },
  createdCount: 12,
  ownedCount: 3,
  collectionCount: 5,
  createdTabInfo: [
      {
          id: 1,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Ocean's Echo",
          titleFa: "طنین اقیانوس",
          price: "9.72",
          highestBid: "0.87",
      },
      {
          id: 2,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Tidal Wave",
          titleFa: "موج جزر و مد",
          price: "8.53",
          highestBid: "0.74",
      },
      {
          id: 3,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Blue Abyss",
          titleFa: "عمق آبی",
          price: "6.49",
          highestBid: "0.66",
      },
      {
          id: 4,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Beneath the Surface",
          titleFa: "زیر سطح",
          price: "7.89",
          highestBid: "0.79",
      },
      {
          id: 5,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Whale Song",
          titleFa: "آواز نهنگ",
          price: "8.24",
          highestBid: "0.85",
      },
      {
          id: 6,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Endless Horizon",
          titleFa: "افق بی‌پایان",
          price: "6.18",
          highestBid: "0.61",
      },
      {
          id: 7,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Deep Blue",
          titleFa: "آبی عمیق",
          price: "7.65",
          highestBid: "0.78",
      },
      {
          id: 8,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Currents of Time",
          titleFa: "جریان‌های زمان",
          price: "6.93",
          highestBid: "0.69",
      },
      {
          id: 9,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Lost in Waves",
          titleFa: "گم شده در امواج",
          price: "8.43",
          highestBid: "0.81",
      },
  ],
  ownedTabInfo: [
      {
          id: 1,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Ocean Dreams",
          titleFa: "رویاهای اقیانوسی",
          price: "5.39",
          highestBid: "0.46",
      },
      {
          id: 2,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Hidden Depths",
          titleFa: "عمق‌های پنهان",
          price: "4.72",
          highestBid: "0.51",
      },
      {
          id: 3,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Silent Waters",
          titleFa: "آب‌های خاموش",
          price: "6.12",
          highestBid: "0.65",
      },
      {
          id: 4,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Beyond the Horizon",
          titleFa: "فراتر از افق",
          price: "7.34",
          highestBid: "0.73",
      },
  ],
  collectionTabInfo: [
      {
          id: 1,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Photography",
          titleFa: "عکاسی",
      },
      {
          id: 2,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Music",
          titleFa: "موسیقی",
      },
      {
          id: 3,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Collectibles",
          titleFa: "کلکسیونی‌ها",
      },
      {
          id: 4,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Art",
          titleFa: "هنر",
      },
      {
          id: 5,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Virtual Worlds",
          titleFa: "جهان‌های مجازی",
      },
  ],
},
{
  paramsName: "robotica",
  artistNameEn: "Robotica",
  artistNameFa: "روباتیکا",
  bioEn: "A tech-inspired artist merging robotics with stunning visual art.",
  bioFa: ".هنرمند الهام گرفته از فناوری که روباتیک را با هنر بصری خیره‌کننده ترکیب می‌کند",
  topImage: "CHANGE-IMAGE",
  avatar: "CHANGE-IMAGE",
  achievements: {
      volume: 752,
      soldNFTs: 84,
      followers: 5210
  },
  createdCount: 15,
  ownedCount: 4,
  collectionCount: 3,
  createdTabInfo: [
      {
          id: 1,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Mechanical Dreams",
          titleFa: "رویاهای مکانیکی",
          price: "5.87",
          highestBid: "0.39",
      },
      {
          id: 2,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Digital Symphony",
          titleFa: "سمفونی دیجیتال",
          price: "6.42",
          highestBid: "0.45",
      },
      {
          id: 3,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Code and Color",
          titleFa: "کد و رنگ",
          price: "7.23",
          highestBid: "0.52",
      },
      {
          id: 4,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Futuristic Visions",
          titleFa: "بینش‌های آینده‌نگر",
          price: "6.96",
          highestBid: "0.48",
      },
      {
          id: 5,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Art of Automation",
          titleFa: "هنر اتوماسیون",
          price: "5.34",
          highestBid: "0.36",
      },
      {
          id: 6,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Robo-Realism",
          titleFa: "رئالیسم رباتی",
          price: "6.55",
          highestBid: "0.49",
      },
      {
          id: 7,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Cybernetic Art",
          titleFa: "هنر سایبرنتیکی",
          price: "8.14",
          highestBid: "0.63",
      },
      {
          id: 8,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "The Future is Now",
          titleFa: "آینده همین حالاست",
          price: "7.81",
          highestBid: "0.58",
      },
      {
          id: 9,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Neon Mechanica",
          titleFa: "مکانیک نئونی",
          price: "6.72",
          highestBid: "0.42",
      },
  ],
  ownedTabInfo: [
      {
          id: 1,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Automated Beauty",
          titleFa: "زیبایی خودکار",
          price: "4.23",
          highestBid: "0.30",
      },
      {
          id: 2,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Robot Revolution",
          titleFa: "انقلاب روبات‌ها",
          price: "5.67",
          highestBid: "0.41",
      },
      {
          id: 3,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Binary Vision",
          titleFa: "چشم‌انداز باینری",
          price: "3.98",
          highestBid: "0.26",
      },
      {
          id: 4,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Circuit of Life",
          titleFa: "مدار زندگی",
          price: "4.75",
          highestBid: "0.33",
      },
  ],
  collectionTabInfo: [
      {
          id: 1,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Art",
          titleFa: "هنر",
      },
      {
          id: 2,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Collectibles",
          titleFa: "کلکسیونی‌ها",
      },
      {
          id: 3,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Utility",
          titleFa: "کاربردی",
      },
  ],
},
{
  paramsName: "rustyrobot",
  artistNameEn: "RustyRobot",
  artistNameFa: "روبات زنگ‌زده",
  bioEn: "An artist who breathes life into old machinery through creative art.",
  bioFa: ".هنرمندی که به ماشین‌آلات قدیمی زندگی می‌بخشد از طریق هنر خلاق",
  topImage: "CHANGE-IMAGE",
  avatar: "CHANGE-IMAGE",
  achievements: {
      volume: 512,
      soldNFTs: 67,
      followers: 3924
  },
  createdCount: 10,
  ownedCount: 5,
  collectionCount: 4,
  createdTabInfo: [
      {
          id: 1,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Recycled Dreams",
          titleFa: "رویاهای بازیافتی",
          price: "3.21",
          highestBid: "0.28",
      },
      {
          id: 2,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Mechanical Heart",
          titleFa: "قلب مکانیکی",
          price: "4.15",
          highestBid: "0.35",
      },
      {
          id: 3,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Rusty Memories",
          titleFa: "خاطرات زنگ‌زده",
          price: "5.67",
          highestBid: "0.41",
      },
      {
          id: 4,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Vintage Vibes",
          titleFa: "احساسات قدیمی",
          price: "3.76",
          highestBid: "0.33",
      },
      {
          id: 5,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Old Meets New",
          titleFa: "قدیم در برابر جدید",
          price: "4.89",
          highestBid: "0.37",
      },
      {
          id: 6,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Rusted Soul",
          titleFa: "روح زنگ‌زده",
          price: "5.55",
          highestBid: "0.43",
      },
      {
          id: 7,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Forgotten Machines",
          titleFa: "ماشین‌های فراموش‌شده",
          price: "6.12",
          highestBid: "0.49",
      },
      {
          id: 8,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Art of Decay",
          titleFa: "هنر زوال",
          price: "4.66",
          highestBid: "0.36",
      },
      {
          id: 9,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Worn Out Wonders",
          titleFa: "شگفتی‌های فرسوده",
          price: "5.90",
          highestBid: "0.45",
      },
  ],
  ownedTabInfo: [
      {
          id: 1,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Revived Relics",
          titleFa: "عتیقه‌های زنده‌شده",
          price: "3.88",
          highestBid: "0.31",
      },
      {
          id: 2,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Timeworn Beauty",
          titleFa: "زیبایی زمان‌زده",
          price: "4.41",
          highestBid: "0.38",
      },
      {
          id: 3,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Retro Revival",
          titleFa: "احیای قدیمی",
          price: "3.67",
          highestBid: "0.29",
      },
      {
          id: 4,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Mechanics of Art",
          titleFa: "مکانیک‌های هنر",
          price: "4.92",
          highestBid: "0.36",
      },
  ],
  collectionTabInfo: [
      {
          id: 1,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Collectibles",
          titleFa: "کلکسیونی‌ها",
      },
      {
          id: 2,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Art",
          titleFa: "هنر",
      },
      {
          id: 3,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Utility",
          titleFa: "کاربردی",
      },
      {
          id: 4,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Vintage",
          titleFa: "قدیمی",
      },
  ],
},
{
  paramsName: "moondancer",
  artistNameEn: "MoonDancer",
  artistNameFa: "رقصنده ماه",
  bioEn: "Dancing under the moonlight, creating magical visuals.",
  bioFa: ".رقصیدن زیر نور ماه و خلق تصاویر جادویی",
  topImage: "CHANGE-IMAGE",
  avatar: "CHANGE-IMAGE",
  achievements: {
      volume: 789,
      soldNFTs: 65,
      followers: 7300
  },
  createdCount: 15,
  ownedCount: 2,
  collectionCount: 6,
  createdTabInfo: [
      {
          id: 1,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Lunar Whispers",
          titleFa: "پچ‌پچه‌های قمری",
          price: "7.32",
          highestBid: "0.70",
      },
      {
          id: 2,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Moonlit Nights",
          titleFa: "شب‌های نورانی ماه",
          price: "8.15",
          highestBid: "0.64",
      },
      {
          id: 3,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Dancing Stars",
          titleFa: "ستاره‌های رقصان",
          price: "6.89",
          highestBid: "0.57",
      },
      {
          id: 4,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Cosmic Dreams",
          titleFa: "رویاهای کیهانی",
          price: "9.45",
          highestBid: "0.72",
      },
      {
          id: 5,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Celestial Rhythms",
          titleFa: "آهنگ‌های آسمانی",
          price: "8.99",
          highestBid: "0.75",
      },
      {
          id: 6,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Eclipse of Hearts",
          titleFa: "کسوف قلب‌ها",
          price: "7.67",
          highestBid: "0.69",
      },
      {
          id: 7,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Starlit Pathways",
          titleFa: "راه‌های ستاره‌ای",
          price: "6.33",
          highestBid: "0.55",
      },
      {
          id: 8,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Nighttime Serenade",
          titleFa: "سرناد شبانه",
          price: "7.81",
          highestBid: "0.62",
      },
      {
          id: 9,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Mystical Orbs",
          titleFa: "کره‌های مرموز",
          price: "9.12",
          highestBid: "0.74",
      },
  ],
  ownedTabInfo: [
      {
          id: 1,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Echoes of the Moon",
          titleFa: "طنین‌های ماه",
          price: "8.41",
          highestBid: "0.66",
      },
      {
          id: 2,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Galactic Dancer",
          titleFa: "رقصنده کهکشان",
          price: "7.58",
          highestBid: "0.59",
      },
      {
          id: 3,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Lunar Embrace",
          titleFa: "آغوش ماه",
          price: "9.25",
          highestBid: "0.70",
      },
      {
          id: 4,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Chasing Stars",
          titleFa: "دنبال کردن ستاره‌ها",
          price: "8.88",
          highestBid: "0.63",
      },
  ],
  collectionTabInfo: [
      {
          id: 1,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Art",
          titleFa: "هنر",
      },
      {
          id: 2,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Collectibles",
          titleFa: "کلکسیونی‌ها",
      },
      {
          id: 3,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Fantasy",
          titleFa: "فانتزی",
      },
      {
          id: 4,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Nature",
          titleFa: "طبیعت",
      },
      {
          id: 5,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Cosmic",
          titleFa: "کیهانی",
      },
      {
          id: 6,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Dreams",
          titleFa: "رویاها",
      },
  ],
},
{
  paramsName: "ghiblier",
  artistNameEn: "Ghiblier",
  artistNameFa: "غیبیلیئر",
  bioEn: "Fusing elements of nature and fantasy into breathtaking visuals.",
  bioFa: ".ترکیب عناصر طبیعت و فانتزی در تصاویر خیره‌کننده",
  topImage: "CHANGE-IMAGE",
  avatar: "CHANGE-IMAGE",
  achievements: {
      volume: 675,
      soldNFTs: 77,
      followers: 6200
  },
  createdCount: 14,
  ownedCount: 4,
  collectionCount: 3,
  createdTabInfo: [
      {
          id: 1,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Whimsical Forests",
          titleFa: "جنگل‌های خیال‌انگیز",
          price: "6.28",
          highestBid: "0.52",
      },
      {
          id: 2,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Mystic Waters",
          titleFa: "آب‌های مرموز",
          price: "5.49",
          highestBid: "0.44",
      },
      {
          id: 3,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Celestial Dreams",
          titleFa: "رویاهای آسمانی",
          price: "7.01",
          highestBid: "0.58",
      },
      {
          id: 4,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Ethereal Landscapes",
          titleFa: "چشم‌اندازهای اترال",
          price: "5.85",
          highestBid: "0.48",
      },
      {
          id: 5,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Nature's Embrace",
          titleFa: "آغوش طبیعت",
          price: "6.66",
          highestBid: "0.53",
      },
      {
          id: 6,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Fantasy Realms",
          titleFa: "دنیای فانتزی",
          price: "7.22",
          highestBid: "0.60",
      },
      {
          id: 7,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Dreamlike Scenery",
          titleFa: "مناظر رویایی",
          price: "6.88",
          highestBid: "0.54",
      },
      {
          id: 8,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Hidden Wonders",
          titleFa: "شگفتی‌های پنهان",
          price: "5.72",
          highestBid: "0.46",
      },
      {
          id: 9,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Fantastical Beasts",
          titleFa: "حیوانات فانتزی",
          price: "8.03",
          highestBid: "0.67",
      },
  ],
  ownedTabInfo: [
      {
          id: 1,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Elemental Forces",
          titleFa: "نیروهای عنصر",
          price: "5.00",
          highestBid: "0.38",
      },
      {
          id: 2,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Celestial Garden",
          titleFa: "باغ آسمانی",
          price: "6.90",
          highestBid: "0.55",
      },
      {
          id: 3,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Nature's Guardians",
          titleFa: "نگهبانان طبیعت",
          price: "4.67",
          highestBid: "0.41",
      },
      {
          id: 4,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Echoes of Nature",
          titleFa: "طنین‌های طبیعت",
          price: "5.79",
          highestBid: "0.49",
      },
  ],
  collectionTabInfo: [
      {
          id: 1,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Art",
          titleFa: "هنر",
      },
      {
          id: 2,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Collectibles",
          titleFa: "کلکسیونی‌ها",
      },
      {
          id: 3,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Nature",
          titleFa: "طبیعت",
      },
  ],
},
{
  paramsName: "dotgu",
  artistNameEn: "Dotgu",
  artistNameFa: "دات‌گو",
  bioEn: "Creating digital masterpieces one dot at a time.",
  bioFa: ".خلق شاهکارهای دیجیتال نقطه به نقطه",
  topImage: "CHANGE-IMAGE",
  avatar: "CHANGE-IMAGE",
  achievements: {
      volume: 430,
      soldNFTs: 92,
      followers: 5401
  },
  createdCount: 12,
  ownedCount: 3,
  collectionCount: 5,
  createdTabInfo: [
      {
          id: 1,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Pixelated Harmony",
          titleFa: "هماهنگی پیکسلی",
          price: "2.94",
          highestBid: "0.23",
      },
      {
          id: 2,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Colorful Connections",
          titleFa: "اتصالات رنگارنگ",
          price: "3.87",
          highestBid: "0.29",
      },
      {
          id: 3,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Dot and Line",
          titleFa: "نقطه و خط",
          price: "4.65",
          highestBid: "0.37",
      },
      {
          id: 4,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Abstract Patterns",
          titleFa: "الگوهای انتزاعی",
          price: "2.45",
          highestBid: "0.19",
      },
      {
          id: 5,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Geometric Dreams",
          titleFa: "رویاهای هندسی",
          price: "3.25",
          highestBid: "0.26",
      },
      {
          id: 6,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Digital Dance",
          titleFa: "رقص دیجیتال",
          price: "4.12",
          highestBid: "0.33",
      },
      {
          id: 7,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Infinite Loops",
          titleFa: "حلقه‌های بی‌نهایت",
          price: "3.66",
          highestBid: "0.30",
      },
      {
          id: 8,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Vibrant Pixels",
          titleFa: "پیکسل‌های زنده",
          price: "4.50",
          highestBid: "0.35",
      },
      {
          id: 9,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Circle of Life",
          titleFa: "دایره زندگی",
          price: "2.88",
          highestBid: "0.21",
      },
  ],
  ownedTabInfo: [
      {
          id: 1,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Bright Spots",
          titleFa: "نقاط درخشان",
          price: "3.01",
          highestBid: "0.22",
      },
      {
          id: 2,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Fleeting Moments",
          titleFa: "لحظات گذرا",
          price: "4.39",
          highestBid: "0.28",
      },
      {
          id: 3,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Dancing Dots",
          titleFa: "نقاط رقصان",
          price: "2.54",
          highestBid: "0.17",
      },
      {
          id: 4,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Mosaic Memories",
          titleFa: "خاطرات موزاییکی",
          price: "3.87",
          highestBid: "0.25",
      },
  ],
  collectionTabInfo: [
      {
          id: 1,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Art",
          titleFa: "هنر",
      },
      {
          id: 2,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Collectibles",
          titleFa: "کلکسیونی‌ها",
      },
      {
          id: 3,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Utility",
          titleFa: "کاربردی",
      },
      {
          id: 4,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Pixels",
          titleFa: "پیکسل‌ها",
      },
      {
          id: 5,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Abstract",
          titleFa: "انتزاعی",
      },
  ],
},
{
  paramsName: "orbitian",
  artistNameEn: "Orbitian",
  artistNameFa: "مداریان",
  bioEn: "A visionary artist capturing the essence of the universe.",
  bioFa: ".هنرمند بصری که جوهره جهان را ثبت می‌کند",
  topImage: "CHANGE-IMAGE",
  avatar: "CHANGE-IMAGE",
  achievements: {
      volume: 654,
      soldNFTs: 45,
      followers: 6000
  },
  createdCount: 10,
  ownedCount: 4,
  collectionCount: 3,
  createdTabInfo: [
      {
          id: 1,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Orbiting Dreams",
          titleFa: "رویاهای مداری",
          price: "9.25",
          highestBid: "0.68",
      },
      {
          id: 2,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Celestial Paths",
          titleFa: "راه‌های آسمانی",
          price: "7.80",
          highestBid: "0.60",
      },
      {
          id: 3,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Galactic Visions",
          titleFa: "بینش‌های کهکشانی",
          price: "10.00",
          highestBid: "0.75",
      },
      {
          id: 4,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Astral Alignments",
          titleFa: "چیدمان‌های نجومی",
          price: "8.90",
          highestBid: "0.66",
      },
      {
          id: 5,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Lunar Harmony",
          titleFa: "هماهنگی قمری",
          price: "9.15",
          highestBid: "0.71",
      },
      {
          id: 6,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Cosmic Interplay",
          titleFa: "بازی‌های کیهانی",
          price: "8.25",
          highestBid: "0.65",
      },
      {
          id: 7,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Stellar Encounters",
          titleFa: "ملاقات‌های ستاره‌ای",
          price: "9.75",
          highestBid: "0.74",
      },
      {
          id: 8,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Beyond the Orbit",
          titleFa: "فراتر از مدار",
          price: "11.10",
          highestBid: "0.80",
      },
      {
          id: 9,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Echoes of Orbit",
          titleFa: "طنین‌های مداری",
          price: "10.55",
          highestBid: "0.78",
      },
  ],
  ownedTabInfo: [
      {
          id: 1,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Galactic Whisper",
          titleFa: "پچ‌پچه کهکشانی",
          price: "9.20",
          highestBid: "0.69",
      },
      {
          id: 2,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Stellar Radiance",
          titleFa: "درخشش ستاره‌ای",
          price: "8.50",
          highestBid: "0.63",
      },
      {
          id: 3,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Astral Wonders",
          titleFa: "شگفتی‌های نجومی",
          price: "9.95",
          highestBid: "0.72",
      },
      {
          id: 4,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Celestial Legacy",
          titleFa: "میراث آسمانی",
          price: "10.30",
          highestBid: "0.77",
      },
  ],
  collectionTabInfo: [
      {
          id: 1,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Art",
          titleFa: "هنر",
      },
      {
          id: 2,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Collectibles",
          titleFa: "کلکسیونی‌ها",
      },
      {
          id: 3,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Fantasy",
          titleFa: "فانتزی",
      },
      {
          id: 4,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Cosmic",
          titleFa: "کیهانی",
      },
  ],
},
{
  paramsName: "spaceone",
  artistNameEn: "Spaceone",
  artistNameFa: "اسپیس وان",
  bioEn: "Intergalactic artist exploring the vastness of the universe.",
  bioFa: ".هنرمند بین کهکشانی که به کاوش وسعت جهان می‌پردازد",
  topImage: "CHANGE-IMAGE",
  avatar: "CHANGE-IMAGE",
  achievements: {
      volume: 732,
      soldNFTs: 58,
      followers: 7000
  },
  createdCount: 13,
  ownedCount: 5,
  collectionCount: 5,
  createdTabInfo: [
      {
          id: 1,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Galactic Exploration",
          titleFa: "اکتشاف کهکشانی",
          price: "8.99",
          highestBid: "0.69",
      },
      {
          id: 2,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Cosmic Journey",
          titleFa: "سفر کیهانی",
          price: "7.78",
          highestBid: "0.63",
      },
      {
          id: 3,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Interstellar Dreams",
          titleFa: "رویاهای بین ستاره‌ای",
          price: "9.45",
          highestBid: "0.76",
      },
      {
          id: 4,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Stellar Odyssey",
          titleFa: "اودیسه ستاره‌ای",
          price: "10.99",
          highestBid: "0.85",
      },
      {
          id: 5,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Wonders of the Universe",
          titleFa: "شگفتی‌های جهان",
          price: "11.45",
          highestBid: "0.92",
      },
      {
          id: 6,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Nebula Adventures",
          titleFa: "ماجراهای سحابی",
          price: "10.25",
          highestBid: "0.81",
      },
      {
          id: 7,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Cosmic Artistry",
          titleFa: "هنر کیهانی",
          price: "9.15",
          highestBid: "0.70",
      },
      {
          id: 8,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Galaxy's Edge",
          titleFa: "لبه کهکشان",
          price: "10.88",
          highestBid: "0.83",
      },
      {
          id: 9,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Beyond the Stars",
          titleFa: "فراتر از ستاره‌ها",
          price: "12.00",
          highestBid: "0.90",
      },
  ],
  ownedTabInfo: [
      {
          id: 1,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Galactic Guardians",
          titleFa: "نگهبانان کهکشانی",
          price: "9.00",
          highestBid: "0.70",
      },
      {
          id: 2,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Celestial Navigators",
          titleFa: "ناوبران آسمانی",
          price: "8.55",
          highestBid: "0.65",
      },
      {
          id: 3,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Astral Explorers",
          titleFa: "کاوشگران نجومی",
          price: "9.75",
          highestBid: "0.75",
      },
      {
          id: 4,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Cosmic Reflections",
          titleFa: "بازتاب‌های کیهانی",
          price: "10.30",
          highestBid: "0.80",
      },
  ],
  collectionTabInfo: [
      {
          id: 1,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Art",
          titleFa: "هنر",
      },
      {
          id: 2,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Collectibles",
          titleFa: "کلکسیونی‌ها",
      },
      {
          id: 3,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Fantasy",
          titleFa: "فانتزی",
      },
      {
          id: 4,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Cosmic",
          titleFa: "کیهانی",
      },
  ],
},
{
  paramsName: "nebulakid",
  artistNameEn: "NebulaKid",
  artistNameFa: "نوا کودک",
  bioEn: "Exploring the cosmos through vibrant and imaginative art.",
  bioFa: ".کاوش در کیهان با آثار پرجنب و جوش و تخیلی",
  topImage: "CHANGE-IMAGE",
  avatar: "CHANGE-IMAGE",
  achievements: {
      volume: 890,
      soldNFTs: 81,
      followers: 8000
  },
  createdCount: 16,
  ownedCount: 3,
  collectionCount: 4,
  createdTabInfo: [
      {
          id: 1,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Cosmic Adventure",
          titleFa: "ماجراجویی کیهانی",
          price: "9.45",
          highestBid: "0.76",
      },
      {
          id: 2,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Galactic Voyage",
          titleFa: "سفر کهکشانی",
          price: "10.15",
          highestBid: "0.80",
      },
      {
          id: 3,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Nebula Dreams",
          titleFa: "رویاهای سحابی",
          price: "8.92",
          highestBid: "0.73",
      },
      {
          id: 4,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Starlit Journey",
          titleFa: "سفر زیر نور ستاره‌ها",
          price: "9.89",
          highestBid: "0.77",
      },
      {
          id: 5,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Celestial Harmony",
          titleFa: "هماهنگی آسمانی",
          price: "11.00",
          highestBid: "0.84",
      },
      {
          id: 6,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Orbiting Fantasies",
          titleFa: "فانتزی‌های مداری",
          price: "10.75",
          highestBid: "0.82",
      },
      {
          id: 7,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Stellar Reflections",
          titleFa: "بازتاب‌های ستاره‌ای",
          price: "9.15",
          highestBid: "0.70",
      },
      {
          id: 8,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Astral Whispers",
          titleFa: "پچ‌پچه‌های نجومی",
          price: "8.78",
          highestBid: "0.66",
      },
      {
          id: 9,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Nebula's Heart",
          titleFa: "قلب سحابی",
          price: "10.20",
          highestBid: "0.79",
      },
  ],
  ownedTabInfo: [
      {
          id: 1,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Lunar Reflections",
          titleFa: "بازتاب‌های قمری",
          price: "9.70",
          highestBid: "0.74",
      },
      {
          id: 2,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Galactic Guardians",
          titleFa: "نگهبانان کهکشانی",
          price: "10.10",
          highestBid: "0.78",
      },
      {
          id: 3,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Cosmic Connections",
          titleFa: "اتصالات کیهانی",
          price: "8.50",
          highestBid: "0.65",
      },
      {
          id: 4,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Echoes of the Cosmos",
          titleFa: "طنین‌های کیهان",
          price: "9.45",
          highestBid: "0.72",
      },
  ],
  collectionTabInfo: [
      {
          id: 1,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Art",
          titleFa: "هنر",
      },
      {
          id: 2,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Collectibles",
          titleFa: "کلکسیونی‌ها",
      },
      {
          id: 3,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Fantasy",
          titleFa: "فانتزی",
      },
      {
          id: 4,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Cosmic",
          titleFa: "کیهانی",
      },
  ],
},
{
  paramsName: "lydiaculhane",
  artistNameEn: "Lydia Culhane",
  artistNameFa: "لیدیا کلاهان",
  bioEn: "An expressive artist conveying emotions through abstract forms.",
  bioFa: ".هنرمند بیانی که احساسات را از طریق اشکال انتزاعی منتقل می‌کند",
  topImage: "CHANGE-IMAGE",
  avatar: "CHANGE-IMAGE",
  achievements: {
      volume: 600,
      soldNFTs: 35,
      followers: 12000
  },
  createdCount: 15,
  ownedCount: 7,
  collectionCount: 6,
  createdTabInfo: [
      {
          id: 1,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Abstract Emotion",
          titleFa: "احساس انتزاعی",
          price: "11.50",
          highestBid: "1.10",
      },
      {
          id: 2,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Colorful Whispers",
          titleFa: "نجواهای رنگارنگ",
          price: "10.00",
          highestBid: "0.95",
      },
      {
          id: 3,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Inner Thoughts",
          titleFa: "افکار درونی",
          price: "12.25",
          highestBid: "1.20",
      },
      {
          id: 4,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Fragmented Reality",
          titleFa: "واقعیت تکه‌تکه",
          price: "13.50",
          highestBid: "1.25",
      },
      {
          id: 5,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Echoes of Silence",
          titleFa: "طنین سکوت",
          price: "9.75",
          highestBid: "0.85",
      },
      {
          id: 6,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Dreamlike States",
          titleFa: "وضعیت‌های خواب‌گونه",
          price: "11.00",
          highestBid: "1.00",
      },
      {
          id: 7,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Emotional Waves",
          titleFa: "موج‌های احساسی",
          price: "10.50",
          highestBid: "0.90",
      },
      {
          id: 8,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Soul's Journey",
          titleFa: "سفر روح",
          price: "12.50",
          highestBid: "1.15",
      },
      {
          id: 9,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Visions of Light",
          titleFa: "بینش‌های نور",
          price: "14.00",
          highestBid: "1.30",
      },
  ],
  ownedTabInfo: [
      {
          id: 1,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Echoes of the Past",
          titleFa: "طنین‌های گذشته",
          price: "10.00",
          highestBid: "0.95",
      },
      {
          id: 2,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Tangled Thoughts",
          titleFa: "افکار درهم",
          price: "11.50",
          highestBid: "1.05",
      },
      {
          id: 3,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Heart's Whisper",
          titleFa: "نجوای قلب",
          price: "12.75",
          highestBid: "1.15",
      },
      {
          id: 4,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Color of Emotions",
          titleFa: "رنگ احساسات",
          price: "10.25",
          highestBid: "1.00",
      },
  ],
  collectionTabInfo: [
      {
          id: 1,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Art",
          titleFa: "هنر",
      },
      {
          id: 2,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Expressions",
          titleFa: "بیانات",
      },
      {
          id: 3,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Feelings",
          titleFa: "احساسات",
      },
      {
          id: 4,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Abstracts",
          titleFa: "انتزاعی‌ها",
      },
  ],
},
{
  paramsName: "puppypower",
  artistNameEn: "PuppyPower",
  artistNameFa: "قدرت توله‌سگی",
  bioEn: "An artist dedicated to capturing the joy and innocence of puppies.",
  bioFa: ".هنرمند متعهد به ثبت شادی و معصومیت توله‌سگ‌ها",
  topImage: "CHANGE-IMAGE",
  avatar: "CHANGE-IMAGE",
  achievements: {
      volume: 300,
      soldNFTs: 20,
      followers: 8000
  },
  createdCount: 10,
  ownedCount: 5,
  collectionCount: 4,
  createdTabInfo: [
      {
          id: 1,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Happy Puppy",
          titleFa: "توله‌سگ شاد",
          price: "7.50",
          highestBid: "0.60",
      },
      {
          id: 2,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Puppy Love",
          titleFa: "عشق توله‌سگ",
          price: "6.25",
          highestBid: "0.55",
      },
      {
          id: 3,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Joyful Bark",
          titleFa: "پوزه شاد",
          price: "5.00",
          highestBid: "0.50",
      },
      {
          id: 4,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Playful Paws",
          titleFa: "پاهای بازیگوش",
          price: "6.00",
          highestBid: "0.55",
      },
      {
          id: 5,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Puppy Dreams",
          titleFa: "رویاهای توله‌سگی",
          price: "8.00",
          highestBid: "0.70",
      },
      {
          id: 6,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Woof Woof",
          titleFa: "بیا بیا",
          price: "7.25",
          highestBid: "0.65",
      },
      {
          id: 7,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Snuggly Puppy",
          titleFa: "توله‌سگ بغل‌کردنی",
          price: "6.50",
          highestBid: "0.60",
      },
      {
          id: 8,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Happy Tails",
          titleFa: "دم‌های شاد",
          price: "5.75",
          highestBid: "0.55",
      },
      {
          id: 9,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Furry Friends",
          titleFa: "دوستان پشمالو",
          price: "6.90",
          highestBid: "0.70",
      },
  ],
  ownedTabInfo: [
      {
          id: 1,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Sweet Puppy",
          titleFa: "توله‌سگ شیرین",
          price: "7.00",
          highestBid: "0.60",
      },
      {
          id: 2,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Puppy Parade",
          titleFa: "رژه توله‌سگ‌ها",
          price: "6.75",
          highestBid: "0.65",
      },
      {
          id: 3,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Cuddly Pup",
          titleFa: "توله‌سگ بغل‌کردنی",
          price: "7.50",
          highestBid: "0.70",
      },
      {
          id: 4,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Playtime!",
          titleFa: "زمان بازی!",
          price: "6.25",
          highestBid: "0.60",
      },
  ],
  collectionTabInfo: [
      {
          id: 1,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Art",
          titleFa: "هنر",
      },
      {
          id: 2,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Collectibles",
          titleFa: "کلکسیونی‌ها",
      },
      {
          id: 3,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Animals",
          titleFa: "حیوانات",
      },
      {
          id: 4,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Joy",
          titleFa: "شادی",
      },
  ],
},
{
  paramsName: "iceapeclub",
  artistNameEn: "Ice Ape Club",
  artistNameFa: "باشگاه میمون یخی",
  bioEn: "A creative collective celebrating the fun and quirky side of art.",
  bioFa: ".یک کلکسیون خلاقانه که جنبه‌های سرگرم‌کننده و عجیب هنر را جشن می‌گیرد",
  topImage: "CHANGE-IMAGE",
  avatar: "CHANGE-IMAGE",
  achievements: {
      volume: 400,
      soldNFTs: 25,
      followers: 10000
  },
  createdCount: 8,
  ownedCount: 6,
  collectionCount: 3,
  createdTabInfo: [
      {
          id: 1,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Cool Monkey",
          titleFa: "میمون باحال",
          price: "5.00",
          highestBid: "0.50",
      },
      {
          id: 2,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Ice Cream Dream",
          titleFa: "رویای بستنی",
          price: "6.25",
          highestBid: "0.55",
      },
      {
          id: 3,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Chill Vibes",
          titleFa: "احساس آرام",
          price: "4.75",
          highestBid: "0.45",
      },
      {
          id: 4,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Frosty Friends",
          titleFa: "دوستان یخی",
          price: "5.80",
          highestBid: "0.60",
      },
      {
          id: 5,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Snowy Adventure",
          titleFa: "ماجراجویی برفی",
          price: "6.50",
          highestBid: "0.70",
      },
      {
          id: 6,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Polar Party",
          titleFa: "جشن قطبی",
          price: "7.00",
          highestBid: "0.75",
      },
      {
          id: 7,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Winter Wonder",
          titleFa: "شگفتی زمستانی",
          price: "5.50",
          highestBid: "0.55",
      },
      {
          id: 8,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Chill Monkey",
          titleFa: "میمون خنک",
          price: "4.50",
          highestBid: "0.40",
      },
      {
          id: 9,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Funky Ice",
          titleFa: "یخ فنگی",
          price: "6.80",
          highestBid: "0.65",
      },
  ],
  ownedTabInfo: [
      {
          id: 1,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Winter Wonderland",
          titleFa: "سرزمین عجایب زمستانی",
          price: "5.25",
          highestBid: "0.50",
      },
      {
          id: 2,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Ice Age Fun",
          titleFa: "سرگرمی عصر یخ",
          price: "4.90",
          highestBid: "0.45",
      },
      {
          id: 3,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Snowball Fight",
          titleFa: "نبرد برفی",
          price: "5.75",
          highestBid: "0.60",
      },
      {
          id: 4,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Frosty Fun",
          titleFa: "سرگرمی یخی",
          price: "6.20",
          highestBid: "0.55",
      },
  ],
  collectionTabInfo: [
      {
          id: 1,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Art",
          titleFa: "هنر",
      },
      {
          id: 2,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Collectibles",
          titleFa: "کلکسیونی‌ها",
      },
      {
          id: 3,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Fun",
          titleFa: "سرگرمی",
      },
      {
          id: 4,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Animals",
          titleFa: "حیوانات",
      },
  ],
},
{
  paramsName: "catch22",
  artistNameEn: "Catch 22",
  artistNameFa: "کچ ۲۲",
  bioEn: "A paradoxical artist exploring themes of life and choice.",
  bioFa: ".هنرمند پارادوکسیکال که به کاوش موضوعات زندگی و انتخاب می‌پردازد",
  topImage: "CHANGE-IMAGE",
  avatar: "CHANGE-IMAGE",
  achievements: {
      volume: 500,
      soldNFTs: 30,
      followers: 9000
  },
  createdCount: 12,
  ownedCount: 4,
  collectionCount: 5,
  createdTabInfo: [
      {
          id: 1,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Life Choices",
          titleFa: "انتخاب‌های زندگی",
          price: "15.00",
          highestBid: "1.50",
      },
      {
          id: 2,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Endless Loop",
          titleFa: "حلقه بی‌پایان",
          price: "12.75",
          highestBid: "1.20",
      },
      {
          id: 3,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "The Illusion",
          titleFa: "توهم",
          price: "10.50",
          highestBid: "0.95",
      },
      {
          id: 4,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Choices Made",
          titleFa: "انتخاب‌های انجام‌شده",
          price: "8.90",
          highestBid: "0.80",
      },
      {
          id: 5,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "The Paradox",
          titleFa: "پارادوکس",
          price: "14.30",
          highestBid: "1.40",
      },
      {
          id: 6,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Fork in the Road",
          titleFa: "انشعاب در جاده",
          price: "11.00",
          highestBid: "1.00",
      },
      {
          id: 7,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "The Dilemma",
          titleFa: "معضل",
          price: "9.00",
          highestBid: "0.70",
      },
      {
          id: 8,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Cycle of Decisions",
          titleFa: "چرخه تصمیمات",
          price: "13.50",
          highestBid: "1.30",
      },
      {
          id: 9,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Living with Choices",
          titleFa: "زیستن با انتخاب‌ها",
          price: "12.00",
          highestBid: "1.10",
      },
  ],
  ownedTabInfo: [
      {
          id: 1,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "The Road Less Traveled",
          titleFa: "راه کمتر پیموده‌شده",
          price: "10.00",
          highestBid: "0.90",
      },
      {
          id: 2,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "In the Balance",
          titleFa: "در تعادل",
          price: "9.50",
          highestBid: "0.85",
      },
      {
          id: 3,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "Breaking Free",
          titleFa: "رهایی",
          price: "11.75",
          highestBid: "1.05",
      },
      {
          id: 4,
          href: "/",
          image: "CHANGE-IMAGE",
          titleEn: "The Unknown",
          titleFa: "ناشناخته",
          price: "12.25",
          highestBid: "1.15",
      },
  ],
  collectionTabInfo: [
      {
          id: 1,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Art",
          titleFa: "هنر",
      },
      {
          id: 2,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Collectibles",
          titleFa: "کلکسیونی‌ها",
      },
      {
          id: 3,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Philosophy",
          titleFa: "فلسفه",
      },
      {
          id: 4,
          href: "/",
          imageMain: "CHANGE-IMAGE",
          topLayerImage: "CHANGE-IMAGE",
          titleEn: "Life",
          titleFa: "زندگی",
      },
  ],
},
];




/*
MrFox
Shroomie
BeKind2Robots
Keepitreal
DigiLab
GravityOne
Juanie
BlueWhale
Robotica
RustyRobot
Dotgu
Ghiblier
MoonDancer
NebulaKid
Spaceone
Orbitian
Catch 22
Ice Ape Club
PuppyPower
Lydia Culhane


Art
Collectibles
Music
Photography
Video
Utility
Sport
Virtual Worlds
*/

/*
const arrayOfObjects = [
  {
    name: "John",
    hobbies: ["reading", "gaming"]
  },
  {
    name: "Alice",
    hobbies: ["painting", "dancing"]
  },
  {
    name: "Bob",
    hobbies: ["swimming", "cycling"]
  },
  {
    name: "Eve",
    hobbies: ["cooking", "hiking"]
  }
];
*/

export const nfts = [
  {
    paramsName: "the-orbitians",
    artistNameEn: "The Orbitians",
    artistNameFa: "مدارگردها",
    releaseDate: "Sep 30, 2022",
    createdArtistEn: "Orbitian",
    createdArtistFa: "مداری",
    artistHref: "artist/orbitians",
    descriptionEn: "The Orbitians is a collection of 10,000 unique NFTs on the Ethereum blockchain, There are all sorts of beings in the NFT Universe. The most advanced and friendly of the bunch are Orbitians. These Orbitians are a peaceful race, but they have been at war with a group of invaders for many generations. The invaders are called Upside-Downs, because of their inverted bodies that live on the ground, yet do not know any other way to be. Upside-Downs believe that they will be able to win this war if they could only get an eye into Orbitian territory, so they've taken to make human beings their target.",
    descriptionFa: "مدارگردها مجموعه ای از 10000 توکن منحصر به فرد در بلاک چین اتریوم است، همه نوع موجودی در جهان توکن وجود دارد. پیشرفته ترین و دوستانه ترین آنها مدارها هستند. آنها در یک ماشین فضایی فلزی در بالای آسمان زندگی می کنند و فقط یک پا روی زمین دارند. این مدار ها یک نژاد صلح آمیز هستند، اما آنها برای نسل های زیادی با گروهی از مهاجمان در جنگ بوده اند. مهاجمان وارونه نامیده می شوند، زیرا بدن های وارونه آنها روی زمین زندگی می کنند، اما راه دیگری برای بودن نمی دانند. وارونه ها بر این باورند که در صورتی می توانند در این جنگ پیروز شوند که فقط بتوانند چشمی به قلمرو مداری بیندازند، بنابراین تلاش کرده اند تا انسان ها را هدف خود قرار دهند",
    topImage: "sunset-dimension-two.jpg",
    artistImage: "rustyrobot-avatar.jpg",
  },
]